available_text_models: [ "gpt-4.1", "gpt-4.1-mini", "gpt-4.1-nano", "gpt-4o"]

info:

  gpt-4.1:
    type: chat_completion
    name: GPT-4.1
    description: The flagship model, designed for maximum coding and instruction‑following performance
    scores:
      quality: 5
      speed: 3
      price: 2
    price_per_1000_input_tokens: 0.02
    price_per_1000_output_tokens: 0.08

  gpt-4.1-mini:
    type: chat_completion
    name: GPT-4.1 Mini
    description: A fast, more compact model that still maintains impressive coding and instruction‑following capabilities
    scores:
      quality: 4
      speed: 4
      price: 4
    price_per_1000_input_tokens: 0.0004
    price_per_1000_output_tokens: 0.0016

  gpt-4.1-nano:
    type: chat_completion
    name: GPT-4.1 Nano
    description: The smallest and fastest of the three, optimized for tasks requiring extremely low latency, and still equipped with a 1‑million‑token context window
    scores:
      quality: 3
      speed: 5
      price: 5
    price_per_1000_input_tokens: 0.0025
    price_per_1000_output_tokens: 0.01

  gpt-4o:
    type: chat_completion
    name: GPT-4o
    description: Advanced multimodal model with vision capabilities for image understanding and analysis
    scores:
      quality: 5
      speed: 4
      price: 3
    price_per_1000_input_tokens: 0.03
    price_per_1000_output_tokens: 0.06

  dalle-3:
    type: image
    price_per_1_image: 0.018  # 512x512

  whisper:
    type: audio
    price_per_1_min: 0.006
